name: bolt11_decoder
description: A decoder for BOLT11 invoices

# version: 1.0.0
# homepage: https://github.com/fusion44/dart_bolt11_decoder
# author: Stefan Stammberger <some.fusion@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  bech32: 
    git: https://github.com/fusion44/bech32
  decimal: ^0.3.0
  fixnum: ^0.10.9
  
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
